[package]
name = "wgsl-language-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.6"
js-sys = "0.3.53"
lsp-types = "0.90.0"
naga = { version = "0.12.2", features = ["wgsl-in", "validate", "span"] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.3.1"
wasm-bindgen = "0.2.76"
